# Generated by Django 4.2.7 on 2024-08-20 08:09

import django.contrib.postgres.fields
from django.db import (
    migrations,
    models,
)

import addon_service.external_storage_service.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalstorageservice",
            name="int_supported_features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    validators=[
                        addon_service.external_storage_service.models.validate_supported_features
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
